name: twenty

services:
  server:
    image: twentycrm/twenty:${TAG:-latest}
    user: root
    volumes:
      - server-local-data:/app/packages/twenty-server/.local-storage
      - docker-data:/app/docker-data
    expose:
      - "3000"
    labels:
      - caddy=https://twenty.synthtrix.com
      - caddy.reverse_proxy={{upstreams 3000}}
    networks:
      - default
      - coolify
    environment:
      NODE_PORT: 3000
      PG_DATABASE_URL: postgres://${PG_DATABASE_USER:-postgres}:${PG_DATABASE_PASSWORD:-postgres}@db:5432/default
      SERVER_URL: ${SERVER_URL}
      REDIS_URL: redis://10.0.4.10:6379
      APP_SECRET: ${APP_SECRET}
      STORAGE_TYPE: local
      DISABLE_DB_MIGRATIONS: "false"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3000/healthz
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 60s
    restart: always

  worker:
    image: twentycrm/twenty:${TAG:-latest}
    volumes:
      - server-local-data:/app/packages/twenty-server/.local-storage
    command: ["yarn", "worker:prod"]
    environment:
      PG_DATABASE_URL: postgres://${PG_DATABASE_USER:-postgres}:${PG_DATABASE_PASSWORD:-postgres}@db:5432/default
      SERVER_URL: ${SERVER_URL}
      REDIS_URL: redis://10.0.4.10:6379
      APP_SECRET: ${APP_SECRET}
      DISABLE_DB_MIGRATIONS: "true"
    depends_on:
      db:
        condition: service_healthy
      server:
        condition: service_started
    restart: always

  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: default
      POSTGRES_PASSWORD: ${PG_DATABASE_PASSWORD:-postgres}
      POSTGRES_USER: ${PG_DATABASE_USER:-postgres}
    healthcheck:
      test: pg_isready -U ${PG_DATABASE_USER:-postgres} -h localhost -d postgres
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  redis:
    image: redis
    restart: always
    networks:
      default:
        ipv4_address: 10.0.4.10
    command: ["--maxmemory-policy", "noeviction"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  default:
    ipam:
      config:
        - subnet: 10.0.4.0/24
  coolify:
    external: true

volumes:
  docker-data:
  db-data:
  server-local-data:
